# Generated by Django 5.2.9 on 2026-07-23 04:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebhe_bazar', '0002_seed_root_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletChargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ درخواستی (تومان)')),
                ('requested_coins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='سکه درخواستی')),
                ('granted_coins', models.PositiveIntegerField(default=0, verbose_name='سکه واریزی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('card_sent', 'شماره کارت ارسال شد'), ('completed', 'سکه واریز شد'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_card_number', models.CharField(blank=True, max_length=64, verbose_name='شماره کارت اعلامی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='شناسه یا توضیح پرداخت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان واریز سکه')),
                ('coins_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت سکه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazar_charge_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست افزایش اعتبار بازار',
                'verbose_name_plural': 'درخواست\u200cهای افزایش اعتبار بازار',
                'ordering': ('-created_at',),
            },
        ),
    ]
