# Generated by Django 6.0.4 on 2026-09-16 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebhe_bazar', '0003_walletchargerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_payment_method',
            field=models.CharField(choices=[('money', 'پول / کیف پول'), ('coin', 'سکه چالش')], default='money', max_length=10, verbose_name='روش پرداخت انتخابی'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_with',
            field=models.CharField(choices=[('money', 'پول / کیف پول'), ('coin', 'سکه چالش')], default='money', max_length=10, verbose_name='پرداخت شده با'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت واحد (سکه)'),
        ),
        migrations.AddField(
            model_name='product',
            name='coin_price',
            field=models.PositiveIntegerField(blank=True, help_text='در صورتی که خالی باشد، از قیمت اصلی برای سکه استفاده می\u200cشود.', null=True, verbose_name='قیمت به سکه چالش'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_method',
            field=models.CharField(choices=[('coin', 'فقط با سکه چالش'), ('money', 'فقط با پول / اعتبار کیف پول'), ('both', 'هر دو (سکه یا پول - به انتخاب خریدار)')], default='both', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='walletchargerequest',
            name='coins_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت شارژ'),
        ),
        migrations.AlterField(
            model_name='walletchargerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شارژ کیف پول'),
        ),
        migrations.AlterField(
            model_name='walletchargerequest',
            name='granted_coins',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='مبلغ شارژ تایید شده (تومان)'),
        ),
        migrations.AlterField(
            model_name='walletchargerequest',
            name='requested_coins',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='سکه درخواستی (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='walletchargerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('card_sent', 'شماره کارت ارسال شد'), ('completed', 'کیف پول شارژ شد'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
