# Generated by Django 5.2.9 on 2026-05-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='study_goal',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
