# Generated by Django 5.2.9 on 2026-05-19 15:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_rank_point_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اول'), (2, 'دوم'), (3, 'سوم'), (4, 'چهارم'), (5, 'پنجم'), (6, 'ششم'), (7, 'هفتم'), (8, 'هشتم'), (9, 'نهم'), (10, 'دهم'), (11, 'یازدهم'), (12, 'دوازدهم')], default=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[accounts.models.validate_birth_date_range]),
        ),
    ]
