# Generated by Django 6.0.4 on 2026-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('location', models.JSONField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('imam_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('location', models.JSONField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
