# Generated by Django 6.0.4 on 2026-04-26 09:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سیر مطالعاتی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='learning_paths/covers/', verbose_name='تصویر کاور')),
                ('difficulty', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح دشواری')),
                ('publish_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('total_stages', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کل مراحل')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='کل امتیاز قابل کسب')),
            ],
            options={
                'verbose_name': 'سیر مطالعاتی',
                'verbose_name_plural': 'سیرهای مطالعاتی',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='LearningStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مرحله')),
                ('stage_number', models.PositiveSmallIntegerField(verbose_name='شماره مرحله')),
                ('content_type', models.CharField(choices=[('podcast', 'پادکست'), ('lecture', 'سخنرانی'), ('book', 'کتاب'), ('video', 'فیلم'), ('documentary', 'مستند'), ('article', 'مقاله')], max_length=20, verbose_name='نوع محتوا')),
                ('content_link_or_file', models.CharField(blank=True, max_length=500, verbose_name='لینک یا فایل محتوا')),
                ('estimated_study_time', models.PositiveSmallIntegerField(default=0, verbose_name='مدت زمان تقریبی مطالعه (دقیقه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مرحله')),
                ('stage_points', models.PositiveIntegerField(default=100, verbose_name='امتیاز مرحله')),
                ('min_passing_score', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='حداقل نمره قبولی آزمون')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='learning.learningpath', verbose_name='سیر مطالعاتی')),
            ],
            options={
                'verbose_name': 'مرحله سیر مطالعاتی',
                'verbose_name_plural': 'مراحل سیر مطالعاتی',
                'ordering': ('learning_path', 'stage_number'),
                'unique_together': {('learning_path', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='StageQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='شماره نمونه سوال')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نمونه سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('learning_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='learning.learningstage', verbose_name='مرحله سیر مطالعاتی')),
            ],
            options={
                'verbose_name': 'مجموعه سوالات مرحله',
                'verbose_name_plural': 'مجموعه\u200cهای سوالات مرحله',
                'ordering': ('learning_stage', 'set_number'),
                'unique_together': {('learning_stage', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='StageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('question_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='شماره سوال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چهارگزینه\u200cای'), ('true_false', 'صحیح-غلط'), ('short_answer', 'کوتاه پاسخ')], max_length=20, verbose_name='نوع سوال')),
                ('option1', models.CharField(blank=True, max_length=500, verbose_name='گزینه 1')),
                ('option2', models.CharField(blank=True, max_length=500, verbose_name='گزینه 2')),
                ('option3', models.CharField(blank=True, max_length=500, verbose_name='گزینه 3')),
                ('option4', models.CharField(blank=True, max_length=500, verbose_name='گزینه 4')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='پاسخ صحیح')),
                ('question_points', models.PositiveSmallIntegerField(default=2, verbose_name='نمره سوال')),
                ('answer_explanation', models.TextField(blank=True, verbose_name='توضیحات پاسخ')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.stagequestionset', verbose_name='مجموعه سوال')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'ordering': ('question_set', 'question_number'),
                'unique_together': {('question_set', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('stopped', 'متوقف شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('completed_stages_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد مراحل تکمیل شده')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='کل امتیاز کسب شده')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='درصد پیشرفت')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.learningstage', verbose_name='آخرین مرحله فعال')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningpath', verbose_name='سیر مطالعاتی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر در سیر مطالعاتی',
                'verbose_name_plural': 'پیشرفت کاربران در سیرهای مطالعاتی',
                'ordering': ('-started_at',),
                'unique_together': {('user', 'learning_path')},
            },
        ),
        migrations.CreateModel(
            name='UserStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('locked', 'قفل شده'), ('unlocked', 'باز شده'), ('in_study', 'در حال مطالعه'), ('ready_for_exam', 'آماده آزمون'), ('passed', 'قبول شده'), ('failed_previously', 'قبلاً مردود شده')], default='locked', max_length=20, verbose_name='وضعیت')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ باز شدن مرحله')),
                ('started_studying_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع مطالعه')),
                ('completed_studying_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام مطالعه')),
                ('exam_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد دفعات تلاش برای آزمون')),
                ('best_score', models.PositiveSmallIntegerField(default=0, verbose_name='بهترین نمره کسب شده')),
                ('score_earned', models.PositiveIntegerField(default=0, verbose_name='امتیاز کسب شده')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ قبولی')),
                ('last_question_set_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.stagequestionset', verbose_name='آخرین نمونه سوال استفاده شده')),
                ('learning_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningstage', verbose_name='مرحله سیر مطالعاتی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_learning_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='learning.userlearningprogress', verbose_name='پیشرفت کلی کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر در مرحله',
                'verbose_name_plural': 'پیشرفت کاربران در مراحل',
                'ordering': ('user_learning_progress', 'learning_stage__stage_number'),
                'unique_together': {('user_learning_progress', 'learning_stage')},
            },
        ),
        migrations.CreateModel(
            name='UserStageExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='شماره تلاش')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع آزمون')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام آزمون')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='نمره کسب شده (از 20)')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('passed', 'قبول'), ('failed', 'مردود')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='زمان صرف شده (ثانیه)')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.stagequestionset', verbose_name='نمونه سوال استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_stage_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='learning.userstageprogress', verbose_name='پیشرفت کاربر در مرحله')),
            ],
            options={
                'verbose_name': 'آزمون کاربر در مرحله',
                'verbose_name_plural': 'آزمون\u200cهای کاربران در مراحل',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='UserExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_answer', models.CharField(blank=True, max_length=500, verbose_name='پاسخ کاربر')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحیح بودن پاسخ')),
                ('score_earned', models.PositiveSmallIntegerField(default=0, verbose_name='نمره کسب شده')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.stagequestion', verbose_name='سوال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.userstageexam', verbose_name='آزمون کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر به سوال',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران به سوالات',
                'ordering': ('exam', 'question__question_number'),
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
