# Generated by Django 5.2.9 on 2026-05-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='accounts.rank', verbose_name='درجه مربوطه'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='total_points',
            field=models.PositiveIntegerField(default=100, verbose_name='کل امتیاز قابل کسب'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='total_stages',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='تعداد کل مراحل'),
        ),
    ]
