# Generated by Django 5.2.9 on 2026-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningpath_rank_alter_learningpath_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstage',
            name='required_points',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز مورد نیاز برای باز شدن'),
        ),
    ]
