# Generated by Django 5.2.9 on 2026-05-20 05:31

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


def normalize_learning_progress(apps, schema_editor):
    LearningPath = apps.get_model("learning", "LearningPath")
    LearningStage = apps.get_model("learning", "LearningStage")
    UserLearningProgress = apps.get_model("learning", "UserLearningProgress")
    UserStageProgress = apps.get_model("learning", "UserStageProgress")
    User = apps.get_model("accounts", "User")
    Rank = apps.get_model("accounts", "Rank")

    now = timezone.now()
    stage_points = 10

    stages_to_update = []
    for stage in LearningStage.objects.all():
        expected_required_points = max((stage.stage_number or 0) - 1, 0) * stage_points
        changed = False
        if stage.stage_points != stage_points:
            stage.stage_points = stage_points
            changed = True
        if stage.required_points != expected_required_points:
            stage.required_points = expected_required_points
            changed = True
        if changed:
            stages_to_update.append(stage)
    if stages_to_update:
        LearningStage.objects.bulk_update(
            stages_to_update,
            ["stage_points", "required_points"],
        )

    paths_to_update = []
    active_stage_map = {}
    for learning_path in LearningPath.objects.all():
        active_stages = list(
            LearningStage.objects.filter(
                learning_path_id=learning_path.id,
                is_active=True,
            ).order_by("stage_number", "id")
        )
        active_stage_map[learning_path.id] = active_stages
        total_stages = len(active_stages)
        total_points = total_stages * stage_points
        if (
            learning_path.total_stages != total_stages
            or learning_path.total_points != total_points
        ):
            learning_path.total_stages = total_stages
            learning_path.total_points = total_points
            paths_to_update.append(learning_path)
    if paths_to_update:
        LearningPath.objects.bulk_update(
            paths_to_update,
            ["total_stages", "total_points"],
        )

    stage_progresses_to_update = []
    progresses_to_update = []
    user_totals = {}

    for user_progress in UserLearningProgress.objects.all():
        ordered_stages = active_stage_map.get(user_progress.learning_path_id, [])
        existing_progresses = {
            stage_progress.learning_stage_id: stage_progress
            for stage_progress in UserStageProgress.objects.filter(
                user_learning_progress_id=user_progress.id
            )
        }

        completed_count = 0
        total_score = 0
        current_stage_id = None

        for index, stage in enumerate(ordered_stages):
            stage_progress = existing_progresses.get(stage.id)
            if stage_progress is None:
                stage_progress = UserStageProgress.objects.create(
                    user_id=user_progress.user_id,
                    learning_stage_id=stage.id,
                    user_learning_progress_id=user_progress.id,
                    status="locked",
                )
                existing_progresses[stage.id] = stage_progress

            if stage_progress.status == "passed":
                if stage_progress.score_earned != stage_points:
                    stage_progress.score_earned = stage_points
                    stage_progresses_to_update.append(stage_progress)
                completed_count += 1
                total_score += stage_points
                continue

            should_unlock = (
                index == 0
                or existing_progresses[ordered_stages[index - 1].id].status == "passed"
            )

            if should_unlock:
                if stage_progress.status == "locked":
                    stage_progress.status = "unlocked"
                    if not stage_progress.unlocked_at:
                        stage_progress.unlocked_at = now
                    stage_progresses_to_update.append(stage_progress)
                if current_stage_id is None:
                    current_stage_id = stage.id
            elif stage_progress.status != "locked":
                stage_progress.status = "locked"
                stage_progresses_to_update.append(stage_progress)

        total_stage_count = len(ordered_stages)
        if total_stage_count:
            progress_percentage = (
                Decimal(completed_count) / Decimal(total_stage_count)
            ) * Decimal("100.00")
        else:
            progress_percentage = Decimal("0.00")

        status = user_progress.status
        completed_at = user_progress.completed_at
        if total_stage_count and completed_count == total_stage_count:
            status = "completed"
            completed_at = completed_at or now
        elif status == "completed":
            status = "in_progress"
            completed_at = None

        if (
            user_progress.completed_stages_count != completed_count
            or user_progress.total_score != total_score
            or user_progress.current_stage_id != current_stage_id
            or user_progress.progress_percentage != progress_percentage
            or user_progress.status != status
            or user_progress.completed_at != completed_at
        ):
            user_progress.completed_stages_count = completed_count
            user_progress.total_score = total_score
            user_progress.current_stage_id = current_stage_id
            user_progress.progress_percentage = progress_percentage
            user_progress.status = status
            user_progress.completed_at = completed_at
            progresses_to_update.append(user_progress)

        user_totals[user_progress.user_id] = (
            user_totals.get(user_progress.user_id, 0) + total_score
        )

    if stage_progresses_to_update:
        unique_stage_progresses = list({progress.id: progress for progress in stage_progresses_to_update}.values())
        UserStageProgress.objects.bulk_update(
            unique_stage_progresses,
            ["status", "unlocked_at", "score_earned"],
        )

    if progresses_to_update:
        UserLearningProgress.objects.bulk_update(
            progresses_to_update,
            [
                "completed_stages_count",
                "total_score",
                "current_stage",
                "progress_percentage",
                "status",
                "completed_at",
            ],
        )

    ranks = list(Rank.objects.order_by("level"))
    users_to_update = []
    for user in User.objects.all():
        total_points = user_totals.get(user.id, 0)
        matched_rank = None
        for rank in ranks:
            if rank.min_points is not None and total_points < rank.min_points:
                continue
            if rank.max_points is None or total_points <= rank.max_points:
                matched_rank = rank
        if user.total_points != total_points or user.current_rank_id != getattr(matched_rank, "id", None):
            user.total_points = total_points
            user.current_rank_id = getattr(matched_rank, "id", None)
            users_to_update.append(user)
    if users_to_update:
        User.objects.bulk_update(users_to_update, ["total_points", "current_rank"])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningstage_detail_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstage',
            name='stage_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='شماره مرحله'),
        ),
        migrations.AlterField(
            model_name='learningstage',
            name='stage_points',
            field=models.PositiveIntegerField(default=10, verbose_name='امتیاز مرحله'),
        ),
        migrations.RunPython(normalize_learning_progress, migrations.RunPython.noop),
    ]
