# Generated by Django 5.2.9 on 2026-04-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان چالش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges/', verbose_name='تصویر چالش')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('coin_reward', models.PositiveIntegerField(verbose_name='مقدار سکه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'چالش',
                'verbose_name_plural': 'چالش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شرکت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='وضعیت تکمیل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('coins_received', models.PositiveIntegerField(default=0, verbose_name='سکه دریافتی')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='challenge_evidence/', verbose_name='مدرک تکمیل')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='challenges.challenge', verbose_name='چالش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت در چالش',
                'verbose_name_plural': 'شرکت در چالش\u200cها',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
