# Generated by Django 5.2.9 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="points_reward",
            field=models.PositiveIntegerField(default=0, verbose_name="مقدار امتیاز"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("attendance", "ثبت حضور"),
                    ("text", "نوشتن متن"),
                    ("image", "آپلود عکس"),
                    ("video", "آپلود فیلم"),
                ],
                default="attendance",
                max_length=20,
                verbose_name="نوع چالش",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="attended",
            field=models.BooleanField(default=False, verbose_name="ثبت حضور توسط کاربر"),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="points_received",
            field=models.PositiveIntegerField(default=0, verbose_name="امتیاز دریافتی"),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ بررسی ادمین"),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="reward_awarded",
            field=models.BooleanField(default=False, verbose_name="پاداش پرداخت شده"),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="status",
            field=models.CharField(
                choices=[
                    ("joined", "ثبت\u200cنام"),
                    ("submitted", "ارسال شده"),
                    ("approved", "تایید شده"),
                    ("rejected", "رد شده"),
                ],
                default="joined",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ ارسال"),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="submission_text",
            field=models.TextField(blank=True, default="", verbose_name="متن ارسال شده"),
        ),
    ]

