# Generated by Django 6.0.4 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_challenge_submission_type_and_participation_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeparticipation",
            name="evidence",
            field=models.FileField(blank=True, null=True, upload_to="challenge_evidence/", verbose_name="فایل ارسالی"),
        ),
        migrations.AlterField(
            model_name="challengeparticipation",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="تایید و ثبت نهایی"),
        ),
    ]

